### ISSUE TITLE
LinkedHashMap cannot be cast to S3Event

### ISSUE THREAD

**Issue by shawnjohnson** [mengjiann/aws-lambda-s3#1]
I am getting the following error when I try to run this project.  Any ideas what might be the issue?

```
{
  "errorMessage": "java.util.LinkedHashMap cannot be cast to com.amazonaws.services.lambda.runtime.events.S3Event",
  "errorType": "java.lang.ClassCastException",
  "stackTrace": [
    "com.mj.aws.lambda.s3.AwsLambdaS3Function.apply(AwsLambdaS3Function.java:14)",
    "org.springframework.cloud.function.core.FluxFunction.lambda$apply$0(FluxFunction.java:47)",
    "reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:107)",
    "reactor.core.publisher.FluxJust$WeakScalarSubscription.request(FluxJust.java:90)",
    "reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:159)",
    "reactor.core.publisher.BlockingIterable$SubscriberIterator.onSubscribe(BlockingIterable.java:214)",
    "reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:90)",
    "reactor.core.publisher.FluxJust.subscribe(FluxJust.java:67)",
    "reactor.core.publisher.FluxMapFuseable.subscribe(FluxMapFuseable.java:63)",
    "reactor.core.publisher.BlockingIterable.iterator(BlockingIterable.java:80)",
    "org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.result(SpringBootRequestHandler.java:54)",
    "org.springframework.cloud.function.adapter.aws.SpringBootRequestHandler.handleRequest(SpringBootRequestHandler.java:49)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ]
}
```

**Comment by mengjiann** [comment]
The com.mj.aws.lambda.s3.AwsLambdaS3Function actually takes in a S3Event. May I know how do you run it? Did you upload to the AWS or run locally using localstack?

**Comment by shawnjohnson** [comment]
I ran using this in AWS, using the "Test" feature, and used the event.json as the test event.  I uploaded the -aws appended jar file generated by Maven, and specified the Handler as `com.mj.aws.lambda.s3.AwsLambdaS3FunctionHandler::handleRequest`.

**Comment by mengjiann** [comment]
You will only this: com.mj.aws.lambda.s3.AwsLambdaS3FunctionHandler as the Handler.
Did you copy everything from the event.json to the text event?

`{
  "Records": [
    {
      "eventVersion": "2.0",
      "eventTime": "1970-01-01T00:00:00.000Z",
      "requestParameters": {
        "sourceIPAddress": "127.0.0.1"
      },
      "s3": {
        "configurationId": "testConfigRule",
        "object": {
          "eTag": "0123456789abcdef0123456789abcdef",
          "sequencer": "0A1B2C3D4E5F678901",
          "key": "test.txt",
          "size": 1024
        },
        "bucket": {
          "arn": "arn:aws:s3:::test_bucket",
          "name": "test_bucket",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          }
        },
        "s3SchemaVersion": "1.0"
      },
      "responseElements": {
        "x-amz-id-2": "EXAMPLE123/5678abcdefghijklambdaisawesome/mnopqrstuvwxyzABCDEFGH",
        "x-amz-request-id": "EXAMPLE123456789"
      },
      "awsRegion": "us-east-1",
      "eventName": "ObjectCreated:Put",
      "userIdentity": {
        "principalId": "EXAMPLE"
      },
      "eventSource": "aws:s3"
    }
  ]
}`

or you can configure the actual S3 trigger from any bucket under your AWS account. It is available under the lambda Designer tab. Then you will just need to upload something to the bucket that you configure to trigger the lambda.

**Comment by shawnjohnson** [comment]
Thanks for your response. It looks like the issue was how I had specified the handler.  When I removed the `::handleRequest` from the Handler setting, it got through to AwsLambdaS3Function.java:34, where I got an Access Denied error, but that's something I can resolve.  Thanks so much for your help and for contributing this project as an example of spring-cloud-function used with an S3Event!
